# Generated by Django 5.0.3 on 2024-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_monthmetrics_monthmetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartermetric',
            name='Quarter_ID',
            field=models.IntegerField(),
        ),
    ]
