# Generated by Django 5.0.3 on 2024-03-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quartermetric_quarter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Quarter_ID',
            field=models.IntegerField(),
        ),
    ]
