# Generated by Django 5.0.3 on 2024-03-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lwe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LWE',
            new_name='Bill',
        ),
    ]
