# Generated by Django 5.0.3 on 2024-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_lwe_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=255)),
                ('Elec_Charge', models.FloatField()),
                ('Elec_Charge_Perc', models.FloatField()),
                ('Fixed_Charge', models.FloatField()),
                ('Fixed_Charge_Perc', models.FloatField()),
                ('Meter_Rent', models.FloatField()),
                ('Meter_Rent_Perc', models.FloatField()),
                ('Energy_Charge', models.FloatField()),
                ('Energy_Charge_Perc', models.FloatField()),
                ('Total_Charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuarterMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quarter_ID', models.FloatField()),
                ('Avg_Charge', models.FloatField()),
            ],
        ),
    ]
